version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            # - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            # - ./C:\Users\Camer\PHP Website\nginx\conf.d\default.conf:/etc/nginx/conf.d/nginx.conf
            - ./nginx/conf.d/default.conf/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
    app:
        build:
            # context: .
            dockerfile: ./php/Dockerfile
        volumes:
            - ./app:/app
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'tutorial'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'tutorial'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    mysqldata: {}
